using ScanlineStudio.Abstractions.Sstv;

namespace ScanlineStudio.Core.Sstv.Tests;

/// <summary>
/// Code-review finding on Phase 3 (CW-ID/FSK station-ID subsystem): the consumer-side discrimination
/// in <c>AnalogFmSstvDecoder.TryNarrowFskScan</c> (a station-ID result must NOT <c>Commit()</c> or
/// <c>return true</c>, unlike a real mode-announce lock -- see that method's own doc comment) was
/// verified correct by direct code review, but was completely unexercised: <c>StationIdDecodeEnabled</c>
/// defaulted false everywhere and nothing in the test suite ever set it, so the discriminating branch
/// had never actually executed. This test closes that gap at the real public-API level: a genuine
/// station-ID transmission, generated by this port's own Phase 2 encoder and fed through the same
/// <see cref="AnalogFmSstvDecoder.PushSamples"/> entry point production code uses, must fire
/// <see cref="AnalogFmSstvDecoder.StationIdDecoded"/> WITHOUT also firing
/// <see cref="AnalogFmSstvDecoder.ModeDetected"/>/<see cref="AnalogFmSstvDecoder.DecodeRestarted"/> as
/// a side effect -- proving the "does not commit a mode" half of the contract survives the full
/// pipeline, not just isolated-decoder-level testing (<c>NarrowFskHeaderDecoderStationIdTests</c>).
///
/// Scope note: this does not ALSO prove a station-ID transmission arriving mid-way through an
/// already-in-progress AVT training sequence leaves that training's own state uncorrupted (the
/// scenario the code review's wording most directly evoked) -- constructing that without corrupting
/// AVT's own required training-tone content is substantially more involved and is left as a
/// documented gap, not silently assumed covered by this test.
/// </summary>
public class StationIdDoesNotAbortScanTests
{
    private const int SampleRate = 11025;

    /// <summary>Pads a clip with trailing silence past <see cref="VisHeader.MaxSearchCeilingMs"/> --
    /// unrelated to station-ID itself: <c>AnalogFmSstvDecoder.TryInterleavedHeaderScan</c>'s own
    /// race-safety gate (Band-1 S3 fix, see that method's doc comment) holds `scanBound` at 0 until
    /// enough total audio has arrived to know the fixed-window header paths have exhausted their
    /// one-shot try -- true for ANY pre-lock scan, not specific to this feature. A station-ID-only
    /// clip (~1.1s) is shorter than the real `MaxSearchCeilingMs` (1305ms at 11025Hz), so without
    /// this padding <see cref="AnalogFmSstvDecoder.TryNarrowFskScan"/> never gets to look at the
    /// buffer at all within a single <see cref="AnalogFmSstvDecoder.PushSamples"/> call -- confirmed
    /// by direct diagnosis, not guessed.</summary>
    private static float[] PadPastFixedWindowCeiling(IEnumerable<float> samples)
    {
        var padded = samples.ToList();
        padded.AddRange(new float[SampleRate * 2]); // 2s trailing silence, comfortably > 1305ms
        return padded.ToArray();
    }

    [Fact]
    public void StationIdTransmission_FiresStationIdDecoded_WithoutFiringModeDetectedOrRestarted()
    {
        var segments = FskStationIdEncoder.Generate("W1AW", null);
        var samples = PadPastFixedWindowCeiling(AnalogFmSstvEncoder.RenderSegments(segments, SampleRate));

        var decoder = new AnalogFmSstvDecoder(SampleRate) { StationIdDecodeEnabled = true };
        var stationIdEvents = new List<FskStationIdDecodedInfo>();
        var modeDetectedEvents = new List<SstvModeDefinition>();
        var restartEvents = new List<SstvModeDefinition>();
        decoder.StationIdDecoded += info => stationIdEvents.Add(info);
        decoder.ModeDetected += m => modeDetectedEvents.Add(m);
        decoder.DecodeRestarted += m => restartEvents.Add(m);

        decoder.PushSamples(samples);

        Assert.Single(stationIdEvents);
        Assert.Equal("W1AW", stationIdEvents[0].Callsign);
        Assert.Null(stationIdEvents[0].CompactNr);
        Assert.Null(stationIdEvents[0].NrText);

        Assert.Empty(modeDetectedEvents);
        Assert.Empty(restartEvents);
    }

    [Fact]
    public void StationIdDecodeDisabled_TransmissionProducesNoEventAtAll()
    {
        // StationIdDecodeEnabled defaults false (matching legacy's real default, sstv.h:708 zero-
        // init) -- confirms the property actually gates the real end-to-end pipeline, not just the
        // isolated decoder unit tests. Padding matters here too, not just in the enabled-flag test
        // above: without it, the scan never reaches this audio AT ALL regardless of the flag, so
        // the assertion below would pass vacuously (true even if the flag did nothing) rather than
        // actually proving the flag is what suppressed the event.
        var segments = FskStationIdEncoder.Generate("W1AW", null);
        var samples = PadPastFixedWindowCeiling(AnalogFmSstvEncoder.RenderSegments(segments, SampleRate));

        var decoder = new AnalogFmSstvDecoder(SampleRate); // StationIdDecodeEnabled left at its default
        var stationIdEvents = new List<FskStationIdDecodedInfo>();
        decoder.StationIdDecoded += info => stationIdEvents.Add(info);

        decoder.PushSamples(samples);

        Assert.Empty(stationIdEvents);
    }

    [Fact]
    public void StationIdTransmission_ThrowingFirstSubscriber_DoesNotStarveLaterSubscriberOrRepeatScan()
    {
        var segments = FskStationIdEncoder.Generate("W1AW", null);
        var samples = PadPastFixedWindowCeiling(AnalogFmSstvEncoder.RenderSegments(segments, SampleRate));
        using var decoder = new AnalogFmSstvDecoder(SampleRate) { StationIdDecodeEnabled = true };
        var expected = new InvalidOperationException("Injected station-ID subscriber failure.");
        var observed = new List<FskStationIdDecodedInfo>();
        decoder.StationIdDecoded += _ => throw expected;
        decoder.StationIdDecoded += observed.Add;

        var actual = Assert.Throws<InvalidOperationException>(() => decoder.PushSamples(samples));

        Assert.Same(expected, actual);
        Assert.Single(observed);
        Assert.Equal("W1AW", observed[0].Callsign);
        decoder.PushSamples(new float[64]);
        Assert.Single(observed);
    }
}
