using ScanlineStudio.Abstractions.Logbook;
using ScanlineStudio.Abstractions.Radio;

namespace ScanlineStudio.Core.Logbook.Tests;

public sealed class AdifImporterTests
{
    [Fact]
    public void Export_ThenImport_RoundTripsTheRecord()
    {
        var exporter = new AdifExporter();
        var importer = new AdifImporter();
        var original = new QsoRecord(
            "1", "N0CALL",
            new DateTimeOffset(2026, 8, 7, 14, 30, 0, TimeSpan.Zero),
            new DateTimeOffset(2026, 8, 7, 14, 35, 0, TimeSpan.Zero),
            14230000, RadioMode.Usb, "martin1", "59", "58",
            "Alice", "Somewhere", "JO31", "Germany", "Nice signal", null);

        var writer = new StringWriter();
        exporter.Export([original], writer);
        var imported = Assert.Single(importer.Import(new StringReader(writer.ToString())));

        Assert.Equal(original.Callsign, imported.Callsign);
        Assert.Equal(original.StartUtc, imported.StartUtc);
        Assert.Equal(original.EndUtc, imported.EndUtc);
        Assert.Equal(original.FrequencyHz, imported.FrequencyHz);
        Assert.Null(imported.Mode); // MODE=SSTV carries no RF-sideband info
        Assert.Equal(original.SstvModeId, imported.SstvModeId);
        Assert.Equal(original.RstSent, imported.RstSent);
        Assert.Equal(original.RstReceived, imported.RstReceived);
        Assert.Equal(original.Name, imported.Name);
        Assert.Equal(original.Qth, imported.Qth);
        Assert.Equal(original.GridSquare, imported.GridSquare);
        Assert.Equal(original.Country, imported.Country);
        Assert.Equal(original.Notes, imported.Notes);
    }

    [Fact]
    public void Export_ThenImport_NonSstvRadioMode_RoundTripsMode()
    {
        var exporter = new AdifExporter();
        var importer = new AdifImporter();
        var original = new QsoRecord("1", "N0CALL", DateTimeOffset.UtcNow, null, null, RadioMode.Fm, null, null, null, null, null, null, null, null, null);

        var writer = new StringWriter();
        exporter.Export([original], writer);
        var imported = Assert.Single(importer.Import(new StringReader(writer.ToString())));

        Assert.Equal(RadioMode.Fm, imported.Mode);
        Assert.Null(imported.SstvModeId);
    }

    [Fact]
    public void Import_RealWorldShapedThirdPartyFile_ParsesEveryRecordAndPreservesUnmappedFields()
    {
        // Shaped like a real-world export from a generic third-party logger: a free-text header
        // comment before the tags (common in the wild, not just our own writer's style), fields
        // back-to-back with no whitespace on one line, a contest-logger-only field (STX) this app
        // has no QsoRecord property for, and CRLF line endings.
        const string adif = "Generated by Generic Logger v3\r\n" +
            "<ADIF_VER:5>3.1.0<PROGRAMID:13>GenericLogger<EOH>\r\n" +
            "<call:4>W1AW<qso_date:8>20250115<time_on:4>1230<band:3>20m<mode:3>SSB<rst_sent:2>59<rst_rcvd:2>59<gridsquare:6>FN31pr<stx:1>5<eor>\r\n" +
            "<CALL:6>DL2QSK<QSO_DATE:8>20250116<TIME_ON:6>081500<MODE:4>SSTV<SUBMODE:8>SCOTTIE1<COMMENT:9>Good copy<EOR>\r\n";

        var importer = new AdifImporter();
        var records = importer.Import(new StringReader(adif));

        Assert.Equal(2, records.Count);

        var first = records[0];
        Assert.Equal("W1AW", first.Callsign);
        Assert.Equal(new DateTimeOffset(2025, 1, 15, 12, 30, 0, TimeSpan.Zero), first.StartUtc);
        Assert.Equal(RadioMode.Unknown, first.Mode); // "SSB" has no direct RadioMode token
        Assert.Equal("FN31pr", first.GridSquare);
        Assert.NotNull(first.Notes);
        Assert.Contains("STX=5", first.Notes);
        Assert.Contains("BAND=20m", first.Notes);

        var second = records[1];
        Assert.Equal("DL2QSK", second.Callsign);
        Assert.Equal("scottie1", second.SstvModeId);
        Assert.Equal("Good copy", second.Notes);
    }

    [Fact]
    public void Import_MissingRequiredCallField_ThrowsFormatException()
    {
        const string adif = "<ADIF_VER:5>3.1.0<EOH><QSO_DATE:8>20250115<TIME_ON:4>1230<EOR>";

        var importer = new AdifImporter();

        Assert.Throws<FormatException>(() => importer.Import(new StringReader(adif)));
    }

    [Fact]
    public void Import_TimeOnWithSeconds_ParsesCorrectly()
    {
        const string adif = "<EOH><CALL:6>N0CALL<QSO_DATE:8>20260807<TIME_ON:6>143045<EOR>";

        var importer = new AdifImporter();
        var record = Assert.Single(importer.Import(new StringReader(adif)));

        Assert.Equal(new DateTimeOffset(2026, 8, 7, 14, 30, 45, TimeSpan.Zero), record.StartUtc);
    }

    [Fact]
    public void Import_NoHeaderAtAll_StillParsesRecords()
    {
        const string adif = "<CALL:6>N0CALL<QSO_DATE:8>20260807<TIME_ON:4>1200<EOR>";

        var importer = new AdifImporter();
        var record = Assert.Single(importer.Import(new StringReader(adif)));

        Assert.Equal("N0CALL", record.Callsign);
    }
}
