<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="6.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Yoniq.Abstractions\Yoniq.Abstractions.csproj" />
    <ProjectReference Include="..\Yoniq.Core.Audio\Yoniq.Core.Audio.csproj" />
  </ItemGroup>
</Project>
